version: '3.8'
services:
    python-flask:
        container_name: vsnippet-ssrf-regex-bypass-2
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:1337:1337"
