version: '3.8'
services:
    java:
        container_name: vsnippet-xss-classic-35
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:1337:1337"
